### ISSUE TITLE
Iniciando o backend

### ISSUE THREAD

**Issue by radaelilucca** [radaelilucca/MeetApp#1]
# Iniciando o backend do MeetApp

- [x] Organize Folders
- [x] Nodemon and Sucrase
- [x] Setup Docker
- [x] Sequelize
- [x] ESlint, Prettier and EditorConfig
- [x] User Migration
- [x] User Model
- [x] Models Loader
- [x] User create
- [x] Generate hash passwords
- [x] JWT Auth
- [x] Auth middleware
- [x] User update (edit)
- [x] Validating inputs

**Comment by radaelilucca** [comment]
# Sucrase

Permite a utilização de algumas sintaxes novas como a de Import e Export com NodeJS, que ainda não suporta as funcionalidades das versões mais novas do Javascript

**Comment by radaelilucca** [comment]
### Docker

Permite a execução isolada de serviços externos ao app, como bancos de dados. Sendo assim, estes serviços não são instalados diretamente no sistema operacional, facilitando toda e qualquer manutenção necessária.

**Comment by radaelilucca** [comment]
### Sequelize
ORM (object-relational mapper) para NodeJS. Faz o mapeamento de dados relacionais (tabelas, colunas e linhas) para objetos Javascript.

### Migrations
Responsável pela criação, alteração e remoção das tabelas de um banco.
- controle de versão para a base de dados;
- cada arquivo contém instruções para criação, alteração ou remoção de tabelas ou colunas;
- Mantém a database atualizada entre todos os devs do time e também no ambiente de produção;
- Cada arquivo é uma migration e sua ordenação ocorre por data // uma migration não pode depender de outra que acontecerá no futuro

### Arquitetura MVC - Model, View, Controller

**Model**
Armazena a abstração do banco de dados, utilizado pra manipular os dados contidos nas tableas do banco. Não possuem responsabilidades sobre as regras de negocio do App.

**View**
É o retorno ao client, em apps que não utilizam o modelo de API REST este retorno pode ser um HTML, nos casos em que o modelo REST é utilizado, o retorno é apenas um JSON, que será manipulado pelo front-end.

**Controller**
É o ponto de entrada das requisições do App. Uma   rota geralmente está diretamente associada com um método do controller. Contem grande parte das regras de negócio do App.

** A Face de um Controller**

- Classes;
- Sempre retorna um JSON;
- Não chama outro controller/método;
- Quando cria um novo controller?
   Apenas 05 métodos;
     Index ( ) {  } = Mostra todos os users
     show  ( ) {  } = Mostra um único user
     store  ( ) {  } = Cria um novo user
     update ( ) {  } = Atualiza/edita um user 
     delete  ( ) {  } = Deleta um user
   Mesma entidade? (Session, User...)

**Comment by radaelilucca** [comment]
### Criando Migration de Users com Sequelize

**Método UP:** 
A ser criado quando a **migration** for executada.
```
 up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('users', {
      id: {
        type: Sequelize.INTEGER,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
      },
```
**Método DOWN:**
 Executado quando a **migration** é desfeita - Geralmente deleta a tabela.
```
down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('users');
  },
```

### Algumas configurações que podem ser utilizadas utilizadas

**Type: Sequelize.TYPE (STRING, BOOL, INT, DATE...)** 
`Define o tipo dos dados armazenados.`
**allowNull: true or false** 
`Define a possibilidade de deixar este campo em branco.`
**unique: true of false**
`Define o valor como sendo único. Previne o cadastro de emails duplicados por ex.`
**defaultValue**
`Define um valor padrão para um campo da tabela.`
**primaryKey: true**
`Chave de valor unico que identifica exclusivamente cada registro de uma tabela.`

 **Executando a migration**

 Comando: 
`yarn sequelize db:migrate`

1. Garantirá que existe uma tabela chamada SequelizeMeta na DB. Esta tabela guarda quais migrations já foram executadas nesta DB.
2. Busca por qualquer migration não executada. Isto pode ser verificado na SequelizeMeta.
3. Cria uma tabela, neste caso chamada users, com todas as colunas especificadas no arquivo migration

 **Revertendo migrations**

Comando:
`
yarn sequelize db:migrate:undo
`
Desfaz a migration mais recente.

`
yarn sequelize db:migrate:undo:all
`
Desfaz todas as migrations.

`
yarn sequelize db:migrate:undo:all --to xxxxxxxxxxxxx-create-blabla.js
`
Desfaz todas as migrations até uma específica.

**Comment by radaelilucca** [comment]
### Password Encryption  password

**Comment by radaelilucca** [comment]
### JWT Auth

**Comment by radaelilucca** [comment]
## Validando Entrada de Dados

### Validação de dados feita a partir da biblioteca Yup.
Define como os dados precisam ser inseridos, como por ex, tipo de dado (string, int), mínimo de caracteres para senha, formato de email, etc...

**Exemplo de schema**

// a biblioteca Yup foi importada como validate

```
 const schema = validate.object().shape({
      name: validate.string().required(),
      email: validate
        .string()
        .email()
        .required(),
      password: validate
        .string()
        .required()
        .min(6),
    });
    if (!(await schema.isValid(req.body))) {
      return res.status(400).json({ error: 'VALIDATION FAILS' });
    }
```

**Comment by leohmoraes** [comment]
Finalizou a Issue ?
Defina um responsável (você) - Assign
Milestone -> Qual o prazo para as Issues incluidas na Milestone e o objetivo(nome da Milestone)
ex: Finalizar Modulo -> Data (0:00 do dia informado) e quais as Issues fechadas que definem esta meta....
