### ISSUE TITLE
Criar Tags das aulas que tiverem modificacao de arquivos

### ISSUE THREAD

**Issue by leohmoraes** [radaelilucca/MeetApp#2]
A cada final de aula, commit.
Informe o nome da aula (ex: Numero sequencial e titulo)
Na descricao do commit, voce pode descrever algo (o que aprendeu ou copiar os itens do checklist para cá também).
No meu commit estou colocando o link da Issue do respectivo Commit

Uso o source tree, lá com  botão direito tem a opcao depois do commit, 
**criar a TAG** mas na linha de comando pode ser feita assim:
````
Git tag NOME_IDENTIFICADOR
```` 
**Para enviar**
````
git push --follow-tags
````
O real uso da tag é para versionamento, mas fazendo assim podemos dar um checkout na aula X facilmente
````
git checkout NOME_IDENTIFICADOR
````
Leia mais https://git-scm.com/book/pt-br/v1/Git-Essencial-Tagging

**Comment by radaelilucca** [comment]
> A cada final de aula, commit.
> Informe o nome da aula (ex: Numero sequencial e titulo)
> Na descricao do commit, voce pode descrever algo (o que aprendeu ou copiar os itens do checklist para cá também).
> No meu commit estou colocando o link da Issue do respectivo Commit
> 
> Uso o source tree, lá com botão direito tem a opcao depois do commit,
> **criar a TAG** mas na linha de comando pode ser feita assim:
> 
> ```
> Git tag NOME_IDENTIFICADOR
> ```
> 
> **Para enviar**
> 
> ```
> git push --follow-tags
> ```
> 
> O real uso da tag é para versionamento, mas fazendo assim podemos dar um checkout na aula X facilmente
> 
> ```
> git checkout NOME_IDENTIFICADOR
> ```
> 
> Leia mais https://git-scm.com/book/pt-br/v1/Git-Essencial-Tagging
